import type { Metadata } from "next";
import { ArrowUpLeft, MapPin, Phone, Clock3 } from "lucide-react";
import { Breadcrumbs } from "@/components/site-shell";
import { WhatsAppIcon } from "@/components/icons";
import { site } from "@/lib/site";

export const metadata: Metadata = { title: "الموقع والتواصل | فرع خميس مشيط", description: "عنوان ورقم مركز دار البديع للحجامة في حي النزهة بخميس مشيط، ورابط الحجز عبر واتساب والاتجاهات على خرائط Google.", alternates: { canonical: "/contact" } };

export default function Contact() {
  return <main id="main"><section className="page-hero simple-hero"><div className="container"><Breadcrumbs items={[{ label: "الموقع والتواصل" }]} /><span className="eyebrow light-eyebrow">أقرب مما تتصور</span><h1>مكانك معروف، <span>وخطوتك بسيطة.</span></h1><p>اختر الطريقة المناسبة للتواصل، أو افتح اتجاهات المركز على خرائط Google.</p></div></section>
    <section className="section contact-section"><div className="container contact-grid"><div className="contact-details"><span className="eyebrow">فرع خميس مشيط</span><h2>نحن في <span>حي النزهة.</span></h2><div className="contact-info"><div><span className="contact-icon"><MapPin size={24} /></span><div><h3>العنوان</h3><p>{site.address}</p><a href={site.maps} target="_blank" rel="noopener noreferrer">فتح الاتجاهات <ArrowUpLeft size={16} /></a></div></div><div><span className="contact-icon"><Phone size={24} /></span><div><h3>الهاتف</h3><a href={`tel:${site.phone}`} dir="ltr">{site.displayPhone}</a></div></div><div><span className="contact-icon"><Clock3 size={24} /></span><div><h3>أوقات الزيارة</h3><p>تحقق من ساعات العمل الحالية عبر <a href={site.maps} target="_blank" rel="noopener noreferrer">ملف Google Maps</a>، وتواصل قبل الحضور لتأكيد موعدك.</p></div></div></div><div className="contact-actions"><a className="button button-dark" href={site.whatsapp} target="_blank" rel="noopener noreferrer"><WhatsAppIcon width={21} height={21} /> واتساب الفرع</a><a className="button button-outline-dark" href={`tel:${site.phone}`}><Phone size={18} /> اتصل الآن</a></div></div><div className="map-wrap"><iframe title="خريطة فرع مركز دار البديع للحجامة في خميس مشيط" src={`https://maps.google.com/maps?q=${site.latitude}%2C${site.longitude}&z=16&output=embed`} loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen /><div className="map-caption"><MapPin size={18} /><span>فرع خميس مشيط · حي النزهة</span><a href={site.maps} target="_blank" rel="noopener noreferrer" aria-label="فتح الخريطة في Google Maps"><ArrowUpLeft size={18} /></a></div></div></div></section></main>;
}
